version: "3"
services:
  sql:
    build: ./sql
    volumes:
      - jsx-templating:/var/lib/mysql
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password
  node:
    build: ./backend
    env_file:
      - .env
    ports:
      - 8081:4200
    user: "node"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
volumes:
  jsx-templating: